# Generated by Django 2.1.7 on 2019-03-03 15:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icici', '0002_auto_20190303_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditupi',
            name='account_no',
            field=models.IntegerField(default=datetime.datetime(2019, 3, 4, 15, 31, 12, 332926)),
        ),
        migrations.AlterField(
            model_name='upi',
            name='virtual_address',
            field=models.CharField(max_length=10),
        ),
    ]
