# Generated by Django 2.1.7 on 2019-03-03 15:36

import creditupi.icici.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icici', '0003_auto_20190303_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditupi',
            name='account_no',
            field=models.IntegerField(default=creditupi.icici.models.get_default_my_date),
        ),
    ]
