# Generated by Django 2.1.7 on 2019-03-03 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icici', '0004_auto_20190303_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditupi',
            name='status',
            field=models.CharField(default='P', max_length=1),
        ),
    ]
