# Generated by Django 2.1.7 on 2019-03-03 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icici', '0006_auto_20190303_1544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creditupi',
            old_name='mobile_no',
            new_name='mobile',
        ),
        migrations.AlterField(
            model_name='creditupi',
            name='pin',
            field=models.IntegerField(default=1758),
        ),
    ]
