# Generated by Django 2.1.7 on 2019-03-03 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icici', '0007_auto_20190303_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditupi',
            name='mobile',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='creditupi',
            name='pin',
            field=models.IntegerField(default=2867),
        ),
    ]
