# Generated by Django 2.1.7 on 2019-03-05 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icici', '0009_auto_20190303_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditupi',
            name='limit',
            field=models.IntegerField(default=8000),
        ),
        migrations.AlterField(
            model_name='creditupi',
            name='pin',
            field=models.IntegerField(default=3524),
        ),
    ]
