# Generated by Django 2.1.7 on 2019-03-07 09:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('icici', '0012_auto_20190306_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditupi',
            name='vpa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='icici.Upi'),
        ),
        migrations.AddField(
            model_name='transactions',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='transactions',
            name='modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='transactions',
            name='trans_type',
            field=models.CharField(default='CR', max_length=2),
        ),
        migrations.AlterField(
            model_name='creditupi',
            name='limit',
            field=models.IntegerField(default=10000),
        ),
        migrations.AlterField(
            model_name='creditupi',
            name='pin',
            field=models.IntegerField(default=1259),
        ),
        migrations.AlterField(
            model_name='upi',
            name='virtual_address',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
