# Generated by Django 2.1.7 on 2019-03-19 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icici', '0015_auto_20190307_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditupi',
            name='pin',
            field=models.IntegerField(default=4704),
        ),
    ]
