# Generated by Django 2.1.7 on 2019-03-20 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icici', '0017_auto_20190320_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditupi',
            name='pin',
            field=models.IntegerField(default=1762),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='trans_key',
            field=models.CharField(default=6940621126, max_length=100),
        ),
    ]
